services:


  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fintrack-api
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
    container_name: fintrack-web
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "8080:80"
